"""add id

Revision ID: 5671768a08c9
Revises: a78bddfe272e
Create Date: 2025-10-16 01:07:24.967907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5671768a08c9'
down_revision: Union[str, Sequence[str], None] = 'a78bddfe272e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('persons', sa.Column('person_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_persons_person_id'), 'persons', ['person_id'], unique=True)
    op.create_index(op.f('ix_persons_phone_number'), 'persons', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persons_phone_number'), table_name='persons')
    op.drop_index(op.f('ix_persons_person_id'), table_name='persons')
    op.drop_column('persons', 'person_id')
    op.drop_column('persons', 'hashed_password')
    op.drop_column('persons', 'phone_number')
    # ### end Alembic commands ###
